// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v3/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsIncidentUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INCIDENT_UNSPECIFIED.String() && e.Code == 500
}

func ErrorIncidentUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_INCIDENT_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

func IsIncidentNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INCIDENT_NOT_FOUND.String() && e.Code == 404
}

func ErrorIncidentNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_INCIDENT_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsIncidentAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INCIDENT_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorIncidentAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_INCIDENT_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsIncidentInvalidArgument(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INCIDENT_INVALID_ARGUMENT.String() && e.Code == 400
}

func ErrorIncidentInvalidArgument(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INCIDENT_INVALID_ARGUMENT.String(), fmt.Sprintf(format, args...))
}
