// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/temperate/v1/temperate.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationTemperateServiceAssignRolePermissions = "/temperate.v1.TemperateService/AssignRolePermissions"
const OperationTemperateServiceAssignUserRoles = "/temperate.v1.TemperateService/AssignUserRoles"
const OperationTemperateServiceChangePassword = "/temperate.v1.TemperateService/ChangePassword"
const OperationTemperateServiceCreatePermission = "/temperate.v1.TemperateService/CreatePermission"
const OperationTemperateServiceCreateRole = "/temperate.v1.TemperateService/CreateRole"
const OperationTemperateServiceCreateSSOProvider = "/temperate.v1.TemperateService/CreateSSOProvider"
const OperationTemperateServiceCreateServiceAccount = "/temperate.v1.TemperateService/CreateServiceAccount"
const OperationTemperateServiceCreateUser = "/temperate.v1.TemperateService/CreateUser"
const OperationTemperateServiceDeletePermission = "/temperate.v1.TemperateService/DeletePermission"
const OperationTemperateServiceDeleteRole = "/temperate.v1.TemperateService/DeleteRole"
const OperationTemperateServiceDeleteSSOProvider = "/temperate.v1.TemperateService/DeleteSSOProvider"
const OperationTemperateServiceDeleteServiceAccount = "/temperate.v1.TemperateService/DeleteServiceAccount"
const OperationTemperateServiceDeleteUser = "/temperate.v1.TemperateService/DeleteUser"
const OperationTemperateServiceGetCurrentUser = "/temperate.v1.TemperateService/GetCurrentUser"
const OperationTemperateServiceGetInitialPassword = "/temperate.v1.TemperateService/GetInitialPassword"
const OperationTemperateServiceGetRole = "/temperate.v1.TemperateService/GetRole"
const OperationTemperateServiceGetSSOProvider = "/temperate.v1.TemperateService/GetSSOProvider"
const OperationTemperateServiceGetServiceAccount = "/temperate.v1.TemperateService/GetServiceAccount"
const OperationTemperateServiceGetSystemSettings = "/temperate.v1.TemperateService/GetSystemSettings"
const OperationTemperateServiceGetUser = "/temperate.v1.TemperateService/GetUser"
const OperationTemperateServiceHealth = "/temperate.v1.TemperateService/Health"
const OperationTemperateServiceKickSession = "/temperate.v1.TemperateService/KickSession"
const OperationTemperateServiceListAuditLogs = "/temperate.v1.TemperateService/ListAuditLogs"
const OperationTemperateServiceListPermissionActions = "/temperate.v1.TemperateService/ListPermissionActions"
const OperationTemperateServiceListPermissions = "/temperate.v1.TemperateService/ListPermissions"
const OperationTemperateServiceListRoles = "/temperate.v1.TemperateService/ListRoles"
const OperationTemperateServiceListSSOProviders = "/temperate.v1.TemperateService/ListSSOProviders"
const OperationTemperateServiceListSSOProvidersPublic = "/temperate.v1.TemperateService/ListSSOProvidersPublic"
const OperationTemperateServiceListServiceAccounts = "/temperate.v1.TemperateService/ListServiceAccounts"
const OperationTemperateServiceListSessions = "/temperate.v1.TemperateService/ListSessions"
const OperationTemperateServiceListUsers = "/temperate.v1.TemperateService/ListUsers"
const OperationTemperateServiceLogin = "/temperate.v1.TemperateService/Login"
const OperationTemperateServiceLogout = "/temperate.v1.TemperateService/Logout"
const OperationTemperateServiceRegenerateServiceAccountToken = "/temperate.v1.TemperateService/RegenerateServiceAccountToken"
const OperationTemperateServiceSetRoleInheritances = "/temperate.v1.TemperateService/SetRoleInheritances"
const OperationTemperateServiceUpdatePermission = "/temperate.v1.TemperateService/UpdatePermission"
const OperationTemperateServiceUpdateRole = "/temperate.v1.TemperateService/UpdateRole"
const OperationTemperateServiceUpdateSSOProvider = "/temperate.v1.TemperateService/UpdateSSOProvider"
const OperationTemperateServiceUpdateServiceAccount = "/temperate.v1.TemperateService/UpdateServiceAccount"
const OperationTemperateServiceUpdateSystemSettings = "/temperate.v1.TemperateService/UpdateSystemSettings"
const OperationTemperateServiceUpdateUser = "/temperate.v1.TemperateService/UpdateUser"

type TemperateServiceHTTPServer interface {
	AssignRolePermissions(context.Context, *AssignRolePermissionsRequest) (*Role, error)
	AssignUserRoles(context.Context, *AssignUserRolesRequest) (*User, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*emptypb.Empty, error)
	CreatePermission(context.Context, *CreatePermissionRequest) (*Permission, error)
	CreateRole(context.Context, *CreateRoleRequest) (*Role, error)
	CreateSSOProvider(context.Context, *CreateSSOProviderRequest) (*SSOProvider, error)
	CreateServiceAccount(context.Context, *CreateServiceAccountRequest) (*ServiceAccountTokenReply, error)
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	DeletePermission(context.Context, *DeletePermissionRequest) (*emptypb.Empty, error)
	DeleteRole(context.Context, *DeleteRoleRequest) (*emptypb.Empty, error)
	DeleteSSOProvider(context.Context, *DeleteSSOProviderRequest) (*emptypb.Empty, error)
	DeleteServiceAccount(context.Context, *DeleteServiceAccountRequest) (*emptypb.Empty, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error)
	GetCurrentUser(context.Context, *emptypb.Empty) (*User, error)
	GetInitialPassword(context.Context, *emptypb.Empty) (*InitialPasswordReply, error)
	GetRole(context.Context, *GetRoleRequest) (*Role, error)
	GetSSOProvider(context.Context, *GetSSOProviderRequest) (*SSOProvider, error)
	GetServiceAccount(context.Context, *GetServiceAccountRequest) (*ServiceAccount, error)
	GetSystemSettings(context.Context, *emptypb.Empty) (*SystemSettingsReply, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	Health(context.Context, *emptypb.Empty) (*GetMessageResponse, error)
	KickSession(context.Context, *KickSessionRequest) (*emptypb.Empty, error)
	ListAuditLogs(context.Context, *ListAuditLogsRequest) (*ListAuditLogsReply, error)
	ListPermissionActions(context.Context, *emptypb.Empty) (*ListPermissionActionsReply, error)
	ListPermissions(context.Context, *ListPermissionsRequest) (*ListPermissionsReply, error)
	ListRoles(context.Context, *ListRolesRequest) (*ListRolesReply, error)
	// ListSSOProviders SSO provider management (admin)
	ListSSOProviders(context.Context, *ListSSOProvidersRequest) (*ListSSOProvidersReply, error)
	// ListSSOProvidersPublic SSO provider configuration (public list for login page)
	ListSSOProvidersPublic(context.Context, *emptypb.Empty) (*ListSSOProvidersPublicReply, error)
	ListServiceAccounts(context.Context, *ListServiceAccountsRequest) (*ListServiceAccountsReply, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsReply, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersReply, error)
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	Logout(context.Context, *LogoutRequest) (*emptypb.Empty, error)
	RegenerateServiceAccountToken(context.Context, *RegenerateServiceAccountTokenRequest) (*ServiceAccountTokenReply, error)
	SetRoleInheritances(context.Context, *SetRoleInheritancesRequest) (*Role, error)
	UpdatePermission(context.Context, *UpdatePermissionRequest) (*Permission, error)
	UpdateRole(context.Context, *UpdateRoleRequest) (*Role, error)
	UpdateSSOProvider(context.Context, *UpdateSSOProviderRequest) (*SSOProvider, error)
	UpdateServiceAccount(context.Context, *UpdateServiceAccountRequest) (*ServiceAccount, error)
	UpdateSystemSettings(context.Context, *UpdateSystemSettingsRequest) (*SystemSettingsReply, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
}

func RegisterTemperateServiceHTTPServer(s *http.Server, srv TemperateServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/health", _TemperateService_Health0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/auth/login", _TemperateService_Login0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/auth/logout", _TemperateService_Logout0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/auth/initial-password", _TemperateService_GetInitialPassword0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/auth/change-password", _TemperateService_ChangePassword0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/auth/me", _TemperateService_GetCurrentUser0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/users", _TemperateService_CreateUser0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/users", _TemperateService_ListUsers0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/users/{id}", _TemperateService_GetUser0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/users/{id}", _TemperateService_UpdateUser0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/users/{id}", _TemperateService_DeleteUser0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/users/{user_id}/roles", _TemperateService_AssignUserRoles0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/roles", _TemperateService_CreateRole0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/roles", _TemperateService_ListRoles0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/roles/{id}", _TemperateService_GetRole0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/roles/{id}", _TemperateService_UpdateRole0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/roles/{id}", _TemperateService_DeleteRole0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/roles/{role_id}/permissions", _TemperateService_AssignRolePermissions0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/roles/{role_id}/inheritances", _TemperateService_SetRoleInheritances0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/permissions", _TemperateService_CreatePermission0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/permissions", _TemperateService_ListPermissions0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/permissions/actions", _TemperateService_ListPermissionActions0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/permissions/{id}", _TemperateService_UpdatePermission0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/permissions/{id}", _TemperateService_DeletePermission0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/sso/providers/public", _TemperateService_ListSSOProvidersPublic0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/sso/providers", _TemperateService_ListSSOProviders0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/sso/providers/{id}", _TemperateService_GetSSOProvider0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/sso/providers", _TemperateService_CreateSSOProvider0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/sso/providers/{id}", _TemperateService_UpdateSSOProvider0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/sso/providers/{id}", _TemperateService_DeleteSSOProvider0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/sessions", _TemperateService_ListSessions0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/sessions/{id}/kick", _TemperateService_KickSession0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/audit-logs", _TemperateService_ListAuditLogs0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/settings", _TemperateService_GetSystemSettings0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/settings", _TemperateService_UpdateSystemSettings0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/service-accounts", _TemperateService_CreateServiceAccount0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/service-accounts", _TemperateService_ListServiceAccounts0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/service-accounts/{id}", _TemperateService_GetServiceAccount0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/service-accounts/{id}", _TemperateService_UpdateServiceAccount0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/service-accounts/{id}", _TemperateService_DeleteServiceAccount0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/service-accounts/{id}/regenerate-token", _TemperateService_RegenerateServiceAccountToken0_HTTP_Handler(srv))
}

func _TemperateService_Health0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceHealth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Health(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMessageResponse)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_Login0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_Logout0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceLogout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Logout(ctx, req.(*LogoutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_GetInitialPassword0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceGetInitialPassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetInitialPassword(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InitialPasswordReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_ChangePassword0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChangePasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceChangePassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ChangePassword(ctx, req.(*ChangePasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_GetCurrentUser0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceGetCurrentUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCurrentUser(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_CreateUser0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceCreateUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateUser(ctx, req.(*CreateUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_ListUsers0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUsersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceListUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUsers(ctx, req.(*ListUsersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUsersReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_GetUser0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceGetUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUser(ctx, req.(*GetUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_UpdateUser0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceUpdateUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUser(ctx, req.(*UpdateUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_DeleteUser0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceDeleteUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteUser(ctx, req.(*DeleteUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_AssignUserRoles0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignUserRolesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceAssignUserRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignUserRoles(ctx, req.(*AssignUserRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_CreateRole0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceCreateRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRole(ctx, req.(*CreateRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Role)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_ListRoles0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRolesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceListRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRoles(ctx, req.(*ListRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRolesReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_GetRole0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceGetRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRole(ctx, req.(*GetRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Role)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_UpdateRole0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceUpdateRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateRole(ctx, req.(*UpdateRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Role)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_DeleteRole0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceDeleteRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteRole(ctx, req.(*DeleteRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_AssignRolePermissions0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignRolePermissionsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceAssignRolePermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignRolePermissions(ctx, req.(*AssignRolePermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Role)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_SetRoleInheritances0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetRoleInheritancesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceSetRoleInheritances)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetRoleInheritances(ctx, req.(*SetRoleInheritancesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Role)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_CreatePermission0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePermissionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceCreatePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePermission(ctx, req.(*CreatePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Permission)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_ListPermissions0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPermissionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceListPermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPermissions(ctx, req.(*ListPermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPermissionsReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_ListPermissionActions0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceListPermissionActions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPermissionActions(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPermissionActionsReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_UpdatePermission0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePermissionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceUpdatePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePermission(ctx, req.(*UpdatePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Permission)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_DeletePermission0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePermissionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceDeletePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeletePermission(ctx, req.(*DeletePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_ListSSOProvidersPublic0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceListSSOProvidersPublic)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSSOProvidersPublic(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSSOProvidersPublicReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_ListSSOProviders0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSSOProvidersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceListSSOProviders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSSOProviders(ctx, req.(*ListSSOProvidersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSSOProvidersReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_GetSSOProvider0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSSOProviderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceGetSSOProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSSOProvider(ctx, req.(*GetSSOProviderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SSOProvider)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_CreateSSOProvider0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSSOProviderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceCreateSSOProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSSOProvider(ctx, req.(*CreateSSOProviderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SSOProvider)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_UpdateSSOProvider0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSSOProviderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceUpdateSSOProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSSOProvider(ctx, req.(*UpdateSSOProviderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SSOProvider)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_DeleteSSOProvider0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSSOProviderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceDeleteSSOProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSSOProvider(ctx, req.(*DeleteSSOProviderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_ListSessions0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSessionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceListSessions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSessions(ctx, req.(*ListSessionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSessionsReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_KickSession0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in KickSessionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceKickSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.KickSession(ctx, req.(*KickSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_ListAuditLogs0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAuditLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceListAuditLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAuditLogs(ctx, req.(*ListAuditLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAuditLogsReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_GetSystemSettings0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceGetSystemSettings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSystemSettings(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SystemSettingsReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_UpdateSystemSettings0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSystemSettingsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceUpdateSystemSettings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSystemSettings(ctx, req.(*UpdateSystemSettingsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SystemSettingsReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_CreateServiceAccount0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateServiceAccountRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceCreateServiceAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateServiceAccount(ctx, req.(*CreateServiceAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ServiceAccountTokenReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_ListServiceAccounts0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListServiceAccountsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceListServiceAccounts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListServiceAccounts(ctx, req.(*ListServiceAccountsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListServiceAccountsReply)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_GetServiceAccount0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetServiceAccountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceGetServiceAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetServiceAccount(ctx, req.(*GetServiceAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ServiceAccount)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_UpdateServiceAccount0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateServiceAccountRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceUpdateServiceAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateServiceAccount(ctx, req.(*UpdateServiceAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ServiceAccount)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_DeleteServiceAccount0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteServiceAccountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceDeleteServiceAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteServiceAccount(ctx, req.(*DeleteServiceAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TemperateService_RegenerateServiceAccountToken0_HTTP_Handler(srv TemperateServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegenerateServiceAccountTokenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTemperateServiceRegenerateServiceAccountToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegenerateServiceAccountToken(ctx, req.(*RegenerateServiceAccountTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ServiceAccountTokenReply)
		return ctx.Result(200, reply)
	}
}

type TemperateServiceHTTPClient interface {
	AssignRolePermissions(ctx context.Context, req *AssignRolePermissionsRequest, opts ...http.CallOption) (rsp *Role, err error)
	AssignUserRoles(ctx context.Context, req *AssignUserRolesRequest, opts ...http.CallOption) (rsp *User, err error)
	ChangePassword(ctx context.Context, req *ChangePasswordRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	CreatePermission(ctx context.Context, req *CreatePermissionRequest, opts ...http.CallOption) (rsp *Permission, err error)
	CreateRole(ctx context.Context, req *CreateRoleRequest, opts ...http.CallOption) (rsp *Role, err error)
	CreateSSOProvider(ctx context.Context, req *CreateSSOProviderRequest, opts ...http.CallOption) (rsp *SSOProvider, err error)
	CreateServiceAccount(ctx context.Context, req *CreateServiceAccountRequest, opts ...http.CallOption) (rsp *ServiceAccountTokenReply, err error)
	CreateUser(ctx context.Context, req *CreateUserRequest, opts ...http.CallOption) (rsp *User, err error)
	DeletePermission(ctx context.Context, req *DeletePermissionRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteRole(ctx context.Context, req *DeleteRoleRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteSSOProvider(ctx context.Context, req *DeleteSSOProviderRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteServiceAccount(ctx context.Context, req *DeleteServiceAccountRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteUser(ctx context.Context, req *DeleteUserRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetCurrentUser(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *User, err error)
	GetInitialPassword(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *InitialPasswordReply, err error)
	GetRole(ctx context.Context, req *GetRoleRequest, opts ...http.CallOption) (rsp *Role, err error)
	GetSSOProvider(ctx context.Context, req *GetSSOProviderRequest, opts ...http.CallOption) (rsp *SSOProvider, err error)
	GetServiceAccount(ctx context.Context, req *GetServiceAccountRequest, opts ...http.CallOption) (rsp *ServiceAccount, err error)
	GetSystemSettings(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *SystemSettingsReply, err error)
	GetUser(ctx context.Context, req *GetUserRequest, opts ...http.CallOption) (rsp *User, err error)
	Health(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *GetMessageResponse, err error)
	KickSession(ctx context.Context, req *KickSessionRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	ListAuditLogs(ctx context.Context, req *ListAuditLogsRequest, opts ...http.CallOption) (rsp *ListAuditLogsReply, err error)
	ListPermissionActions(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListPermissionActionsReply, err error)
	ListPermissions(ctx context.Context, req *ListPermissionsRequest, opts ...http.CallOption) (rsp *ListPermissionsReply, err error)
	ListRoles(ctx context.Context, req *ListRolesRequest, opts ...http.CallOption) (rsp *ListRolesReply, err error)
	// ListSSOProviders SSO provider management (admin)
	ListSSOProviders(ctx context.Context, req *ListSSOProvidersRequest, opts ...http.CallOption) (rsp *ListSSOProvidersReply, err error)
	// ListSSOProvidersPublic SSO provider configuration (public list for login page)
	ListSSOProvidersPublic(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListSSOProvidersPublicReply, err error)
	ListServiceAccounts(ctx context.Context, req *ListServiceAccountsRequest, opts ...http.CallOption) (rsp *ListServiceAccountsReply, err error)
	ListSessions(ctx context.Context, req *ListSessionsRequest, opts ...http.CallOption) (rsp *ListSessionsReply, err error)
	ListUsers(ctx context.Context, req *ListUsersRequest, opts ...http.CallOption) (rsp *ListUsersReply, err error)
	Login(ctx context.Context, req *LoginRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
	Logout(ctx context.Context, req *LogoutRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	RegenerateServiceAccountToken(ctx context.Context, req *RegenerateServiceAccountTokenRequest, opts ...http.CallOption) (rsp *ServiceAccountTokenReply, err error)
	SetRoleInheritances(ctx context.Context, req *SetRoleInheritancesRequest, opts ...http.CallOption) (rsp *Role, err error)
	UpdatePermission(ctx context.Context, req *UpdatePermissionRequest, opts ...http.CallOption) (rsp *Permission, err error)
	UpdateRole(ctx context.Context, req *UpdateRoleRequest, opts ...http.CallOption) (rsp *Role, err error)
	UpdateSSOProvider(ctx context.Context, req *UpdateSSOProviderRequest, opts ...http.CallOption) (rsp *SSOProvider, err error)
	UpdateServiceAccount(ctx context.Context, req *UpdateServiceAccountRequest, opts ...http.CallOption) (rsp *ServiceAccount, err error)
	UpdateSystemSettings(ctx context.Context, req *UpdateSystemSettingsRequest, opts ...http.CallOption) (rsp *SystemSettingsReply, err error)
	UpdateUser(ctx context.Context, req *UpdateUserRequest, opts ...http.CallOption) (rsp *User, err error)
}

type TemperateServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTemperateServiceHTTPClient(client *http.Client) TemperateServiceHTTPClient {
	return &TemperateServiceHTTPClientImpl{client}
}

func (c *TemperateServiceHTTPClientImpl) AssignRolePermissions(ctx context.Context, in *AssignRolePermissionsRequest, opts ...http.CallOption) (*Role, error) {
	var out Role
	pattern := "/v1/roles/{role_id}/permissions"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceAssignRolePermissions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) AssignUserRoles(ctx context.Context, in *AssignUserRolesRequest, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/v1/users/{user_id}/roles"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceAssignUserRoles),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/auth/change-password"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceChangePassword),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...http.CallOption) (*Permission, error) {
	var out Permission
	pattern := "/v1/permissions"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceCreatePermission),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...http.CallOption) (*Role, error) {
	var out Role
	pattern := "/v1/roles"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceCreateRole),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) CreateSSOProvider(ctx context.Context, in *CreateSSOProviderRequest, opts ...http.CallOption) (*SSOProvider, error) {
	var out SSOProvider
	pattern := "/v1/sso/providers"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceCreateSSOProvider),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) CreateServiceAccount(ctx context.Context, in *CreateServiceAccountRequest, opts ...http.CallOption) (*ServiceAccountTokenReply, error) {
	var out ServiceAccountTokenReply
	pattern := "/v1/service-accounts"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceCreateServiceAccount),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/v1/users"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceCreateUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) DeletePermission(ctx context.Context, in *DeletePermissionRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/permissions/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceDeletePermission),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/roles/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceDeleteRole),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) DeleteSSOProvider(ctx context.Context, in *DeleteSSOProviderRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/sso/providers/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceDeleteSSOProvider),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) DeleteServiceAccount(ctx context.Context, in *DeleteServiceAccountRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/service-accounts/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceDeleteServiceAccount),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/users/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceDeleteUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) GetCurrentUser(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/v1/auth/me"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceGetCurrentUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) GetInitialPassword(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*InitialPasswordReply, error) {
	var out InitialPasswordReply
	pattern := "/v1/auth/initial-password"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceGetInitialPassword),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) GetRole(ctx context.Context, in *GetRoleRequest, opts ...http.CallOption) (*Role, error) {
	var out Role
	pattern := "/v1/roles/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceGetRole),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) GetSSOProvider(ctx context.Context, in *GetSSOProviderRequest, opts ...http.CallOption) (*SSOProvider, error) {
	var out SSOProvider
	pattern := "/v1/sso/providers/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceGetSSOProvider),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) GetServiceAccount(ctx context.Context, in *GetServiceAccountRequest, opts ...http.CallOption) (*ServiceAccount, error) {
	var out ServiceAccount
	pattern := "/v1/service-accounts/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceGetServiceAccount),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) GetSystemSettings(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*SystemSettingsReply, error) {
	var out SystemSettingsReply
	pattern := "/v1/settings"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceGetSystemSettings),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) GetUser(ctx context.Context, in *GetUserRequest, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/v1/users/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceGetUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) Health(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*GetMessageResponse, error) {
	var out GetMessageResponse
	pattern := "/health"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceHealth),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) KickSession(ctx context.Context, in *KickSessionRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/sessions/{id}/kick"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceKickSession),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) ListAuditLogs(ctx context.Context, in *ListAuditLogsRequest, opts ...http.CallOption) (*ListAuditLogsReply, error) {
	var out ListAuditLogsReply
	pattern := "/v1/audit-logs"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceListAuditLogs),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) ListPermissionActions(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListPermissionActionsReply, error) {
	var out ListPermissionActionsReply
	pattern := "/v1/permissions/actions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceListPermissionActions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...http.CallOption) (*ListPermissionsReply, error) {
	var out ListPermissionsReply
	pattern := "/v1/permissions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceListPermissions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...http.CallOption) (*ListRolesReply, error) {
	var out ListRolesReply
	pattern := "/v1/roles"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceListRoles),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSSOProviders SSO provider management (admin)
func (c *TemperateServiceHTTPClientImpl) ListSSOProviders(ctx context.Context, in *ListSSOProvidersRequest, opts ...http.CallOption) (*ListSSOProvidersReply, error) {
	var out ListSSOProvidersReply
	pattern := "/v1/sso/providers"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceListSSOProviders),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSSOProvidersPublic SSO provider configuration (public list for login page)
func (c *TemperateServiceHTTPClientImpl) ListSSOProvidersPublic(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListSSOProvidersPublicReply, error) {
	var out ListSSOProvidersPublicReply
	pattern := "/v1/sso/providers/public"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceListSSOProvidersPublic),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) ListServiceAccounts(ctx context.Context, in *ListServiceAccountsRequest, opts ...http.CallOption) (*ListServiceAccountsReply, error) {
	var out ListServiceAccountsReply
	pattern := "/v1/service-accounts"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceListServiceAccounts),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...http.CallOption) (*ListSessionsReply, error) {
	var out ListSessionsReply
	pattern := "/v1/sessions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceListSessions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...http.CallOption) (*ListUsersReply, error) {
	var out ListUsersReply
	pattern := "/v1/users"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTemperateServiceListUsers),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) Login(ctx context.Context, in *LoginRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/v1/auth/login"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceLogin),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) Logout(ctx context.Context, in *LogoutRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/auth/logout"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceLogout),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) RegenerateServiceAccountToken(ctx context.Context, in *RegenerateServiceAccountTokenRequest, opts ...http.CallOption) (*ServiceAccountTokenReply, error) {
	var out ServiceAccountTokenReply
	pattern := "/v1/service-accounts/{id}/regenerate-token"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceRegenerateServiceAccountToken),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) SetRoleInheritances(ctx context.Context, in *SetRoleInheritancesRequest, opts ...http.CallOption) (*Role, error) {
	var out Role
	pattern := "/v1/roles/{role_id}/inheritances"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceSetRoleInheritances),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) UpdatePermission(ctx context.Context, in *UpdatePermissionRequest, opts ...http.CallOption) (*Permission, error) {
	var out Permission
	pattern := "/v1/permissions/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceUpdatePermission),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...http.CallOption) (*Role, error) {
	var out Role
	pattern := "/v1/roles/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceUpdateRole),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) UpdateSSOProvider(ctx context.Context, in *UpdateSSOProviderRequest, opts ...http.CallOption) (*SSOProvider, error) {
	var out SSOProvider
	pattern := "/v1/sso/providers/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceUpdateSSOProvider),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) UpdateServiceAccount(ctx context.Context, in *UpdateServiceAccountRequest, opts ...http.CallOption) (*ServiceAccount, error) {
	var out ServiceAccount
	pattern := "/v1/service-accounts/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceUpdateServiceAccount),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) UpdateSystemSettings(ctx context.Context, in *UpdateSystemSettingsRequest, opts ...http.CallOption) (*SystemSettingsReply, error) {
	var out SystemSettingsReply
	pattern := "/v1/settings"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceUpdateSystemSettings),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TemperateServiceHTTPClientImpl) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/v1/users/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTemperateServiceUpdateUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
