// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: api/temperate/v1/temperate.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemperateService_Health_FullMethodName = "/temperate.v1.TemperateService/Health"
)

// TemperateServiceClient is the client API for TemperateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemperateServiceClient interface {
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMessageResponse, error)
}

type temperateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTemperateServiceClient(cc grpc.ClientConnInterface) TemperateServiceClient {
	return &temperateServiceClient{cc}
}

func (c *temperateServiceClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageResponse)
	err := c.cc.Invoke(ctx, TemperateService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemperateServiceServer is the server API for TemperateService service.
// All implementations must embed UnimplementedTemperateServiceServer
// for forward compatibility.
type TemperateServiceServer interface {
	Health(context.Context, *emptypb.Empty) (*GetMessageResponse, error)
	mustEmbedUnimplementedTemperateServiceServer()
}

// UnimplementedTemperateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemperateServiceServer struct{}

func (UnimplementedTemperateServiceServer) Health(context.Context, *emptypb.Empty) (*GetMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTemperateServiceServer) mustEmbedUnimplementedTemperateServiceServer() {}
func (UnimplementedTemperateServiceServer) testEmbeddedByValue()                          {}

// UnsafeTemperateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemperateServiceServer will
// result in compilation errors.
type UnsafeTemperateServiceServer interface {
	mustEmbedUnimplementedTemperateServiceServer()
}

func RegisterTemperateServiceServer(s grpc.ServiceRegistrar, srv TemperateServiceServer) {
	// If the following call panics, it indicates UnimplementedTemperateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemperateService_ServiceDesc, srv)
}

func _TemperateService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemperateServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemperateService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemperateServiceServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TemperateService_ServiceDesc is the grpc.ServiceDesc for TemperateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemperateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "temperate.v1.TemperateService",
	HandlerType: (*TemperateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _TemperateService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/temperate/v1/temperate.proto",
}
