// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/auditlog"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/module"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/permission"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/role"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/schema"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/serviceaccount"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/ssoprovider"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/systemsetting"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/user"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/usersession"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogFields[7].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	moduleFields := schema.Module{}.Fields()
	_ = moduleFields
	// moduleDescName is the schema descriptor for name field.
	moduleDescName := moduleFields[0].Descriptor()
	// module.NameValidator is a validator for the "name" field. It is called by the builders before save.
	module.NameValidator = moduleDescName.Validators[0].(func(string) error)
	// moduleDescSystem is the schema descriptor for system field.
	moduleDescSystem := moduleFields[2].Descriptor()
	// module.DefaultSystem holds the default value on creation for the system field.
	module.DefaultSystem = moduleDescSystem.Default.(bool)
	// moduleDescCreatedAt is the schema descriptor for created_at field.
	moduleDescCreatedAt := moduleFields[3].Descriptor()
	// module.DefaultCreatedAt holds the default value on creation for the created_at field.
	module.DefaultCreatedAt = moduleDescCreatedAt.Default.(func() time.Time)
	// moduleDescUpdatedAt is the schema descriptor for updated_at field.
	moduleDescUpdatedAt := moduleFields[4].Descriptor()
	// module.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	module.DefaultUpdatedAt = moduleDescUpdatedAt.Default.(func() time.Time)
	// module.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	module.UpdateDefaultUpdatedAt = moduleDescUpdatedAt.UpdateDefault.(func() time.Time)
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescAction is the schema descriptor for action field.
	permissionDescAction := permissionFields[0].Descriptor()
	// permission.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	permission.ActionValidator = permissionDescAction.Validators[0].(func(string) error)
	// permissionDescSystem is the schema descriptor for system field.
	permissionDescSystem := permissionFields[3].Descriptor()
	// permission.DefaultSystem holds the default value on creation for the system field.
	permission.DefaultSystem = permissionDescSystem.Default.(bool)
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionFields[4].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescUpdatedAt is the schema descriptor for updated_at field.
	permissionDescUpdatedAt := permissionFields[5].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() time.Time)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[0].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescSystem is the schema descriptor for system field.
	roleDescSystem := roleFields[2].Descriptor()
	// role.DefaultSystem holds the default value on creation for the system field.
	role.DefaultSystem = roleDescSystem.Default.(bool)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[3].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleFields[4].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	ssoproviderFields := schema.SSOProvider{}.Fields()
	_ = ssoproviderFields
	// ssoproviderDescName is the schema descriptor for name field.
	ssoproviderDescName := ssoproviderFields[0].Descriptor()
	// ssoprovider.NameValidator is a validator for the "name" field. It is called by the builders before save.
	ssoprovider.NameValidator = ssoproviderDescName.Validators[0].(func(string) error)
	// ssoproviderDescType is the schema descriptor for type field.
	ssoproviderDescType := ssoproviderFields[1].Descriptor()
	// ssoprovider.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	ssoprovider.TypeValidator = ssoproviderDescType.Validators[0].(func(string) error)
	// ssoproviderDescEnabled is the schema descriptor for enabled field.
	ssoproviderDescEnabled := ssoproviderFields[2].Descriptor()
	// ssoprovider.DefaultEnabled holds the default value on creation for the enabled field.
	ssoprovider.DefaultEnabled = ssoproviderDescEnabled.Default.(bool)
	// ssoproviderDescIcon is the schema descriptor for icon field.
	ssoproviderDescIcon := ssoproviderFields[3].Descriptor()
	// ssoprovider.DefaultIcon holds the default value on creation for the icon field.
	ssoprovider.DefaultIcon = ssoproviderDescIcon.Default.(string)
	// ssoproviderDescSortOrder is the schema descriptor for sort_order field.
	ssoproviderDescSortOrder := ssoproviderFields[4].Descriptor()
	// ssoprovider.DefaultSortOrder holds the default value on creation for the sort_order field.
	ssoprovider.DefaultSortOrder = ssoproviderDescSortOrder.Default.(int)
	// ssoproviderDescCreatedAt is the schema descriptor for created_at field.
	ssoproviderDescCreatedAt := ssoproviderFields[6].Descriptor()
	// ssoprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	ssoprovider.DefaultCreatedAt = ssoproviderDescCreatedAt.Default.(func() time.Time)
	// ssoproviderDescUpdatedAt is the schema descriptor for updated_at field.
	ssoproviderDescUpdatedAt := ssoproviderFields[7].Descriptor()
	// ssoprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ssoprovider.DefaultUpdatedAt = ssoproviderDescUpdatedAt.Default.(func() time.Time)
	// ssoprovider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ssoprovider.UpdateDefaultUpdatedAt = ssoproviderDescUpdatedAt.UpdateDefault.(func() time.Time)
	serviceaccountFields := schema.ServiceAccount{}.Fields()
	_ = serviceaccountFields
	// serviceaccountDescName is the schema descriptor for name field.
	serviceaccountDescName := serviceaccountFields[0].Descriptor()
	// serviceaccount.NameValidator is a validator for the "name" field. It is called by the builders before save.
	serviceaccount.NameValidator = serviceaccountDescName.Validators[0].(func(string) error)
	// serviceaccountDescTokenHash is the schema descriptor for token_hash field.
	serviceaccountDescTokenHash := serviceaccountFields[2].Descriptor()
	// serviceaccount.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	serviceaccount.TokenHashValidator = serviceaccountDescTokenHash.Validators[0].(func(string) error)
	// serviceaccountDescTokenPrefix is the schema descriptor for token_prefix field.
	serviceaccountDescTokenPrefix := serviceaccountFields[3].Descriptor()
	// serviceaccount.TokenPrefixValidator is a validator for the "token_prefix" field. It is called by the builders before save.
	serviceaccount.TokenPrefixValidator = serviceaccountDescTokenPrefix.Validators[0].(func(string) error)
	// serviceaccountDescDisabled is the schema descriptor for disabled field.
	serviceaccountDescDisabled := serviceaccountFields[5].Descriptor()
	// serviceaccount.DefaultDisabled holds the default value on creation for the disabled field.
	serviceaccount.DefaultDisabled = serviceaccountDescDisabled.Default.(bool)
	// serviceaccountDescCreatedAt is the schema descriptor for created_at field.
	serviceaccountDescCreatedAt := serviceaccountFields[6].Descriptor()
	// serviceaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	serviceaccount.DefaultCreatedAt = serviceaccountDescCreatedAt.Default.(func() time.Time)
	// serviceaccountDescUpdatedAt is the schema descriptor for updated_at field.
	serviceaccountDescUpdatedAt := serviceaccountFields[7].Descriptor()
	// serviceaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	serviceaccount.DefaultUpdatedAt = serviceaccountDescUpdatedAt.Default.(func() time.Time)
	// serviceaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	serviceaccount.UpdateDefaultUpdatedAt = serviceaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	systemsettingFields := schema.SystemSetting{}.Fields()
	_ = systemsettingFields
	// systemsettingDescKey is the schema descriptor for key field.
	systemsettingDescKey := systemsettingFields[0].Descriptor()
	// systemsetting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	systemsetting.KeyValidator = systemsettingDescKey.Validators[0].(func(string) error)
	// systemsettingDescValue is the schema descriptor for value field.
	systemsettingDescValue := systemsettingFields[1].Descriptor()
	// systemsetting.DefaultValue holds the default value on creation for the value field.
	systemsetting.DefaultValue = systemsettingDescValue.Default.(string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescDisabled is the schema descriptor for disabled field.
	userDescDisabled := userFields[3].Descriptor()
	// user.DefaultDisabled holds the default value on creation for the disabled field.
	user.DefaultDisabled = userDescDisabled.Default.(bool)
	// userDescSystem is the schema descriptor for system field.
	userDescSystem := userFields[4].Descriptor()
	// user.DefaultSystem holds the default value on creation for the system field.
	user.DefaultSystem = userDescSystem.Default.(bool)
	// userDescInitialPasswordUsed is the schema descriptor for initial_password_used field.
	userDescInitialPasswordUsed := userFields[5].Descriptor()
	// user.DefaultInitialPasswordUsed holds the default value on creation for the initial_password_used field.
	user.DefaultInitialPasswordUsed = userDescInitialPasswordUsed.Default.(bool)
	// userDescTotpEnabled is the schema descriptor for totp_enabled field.
	userDescTotpEnabled := userFields[7].Descriptor()
	// user.DefaultTotpEnabled holds the default value on creation for the totp_enabled field.
	user.DefaultTotpEnabled = userDescTotpEnabled.Default.(bool)
	// userDescSource is the schema descriptor for source field.
	userDescSource := userFields[8].Descriptor()
	// user.DefaultSource holds the default value on creation for the source field.
	user.DefaultSource = userDescSource.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[9].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[10].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	usersessionFields := schema.UserSession{}.Fields()
	_ = usersessionFields
	// usersessionDescTokenHash is the schema descriptor for token_hash field.
	usersessionDescTokenHash := usersessionFields[0].Descriptor()
	// usersession.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	usersession.TokenHashValidator = usersessionDescTokenHash.Validators[0].(func(string) error)
	// usersessionDescStatus is the schema descriptor for status field.
	usersessionDescStatus := usersessionFields[4].Descriptor()
	// usersession.DefaultStatus holds the default value on creation for the status field.
	usersession.DefaultStatus = usersessionDescStatus.Default.(string)
	// usersessionDescLoginAt is the schema descriptor for login_at field.
	usersessionDescLoginAt := usersessionFields[6].Descriptor()
	// usersession.DefaultLoginAt holds the default value on creation for the login_at field.
	usersession.DefaultLoginAt = usersessionDescLoginAt.Default.(func() time.Time)
	// usersessionDescLastAccessAt is the schema descriptor for last_access_at field.
	usersessionDescLastAccessAt := usersessionFields[7].Descriptor()
	// usersession.DefaultLastAccessAt holds the default value on creation for the last_access_at field.
	usersession.DefaultLastAccessAt = usersessionDescLastAccessAt.Default.(func() time.Time)
}
