// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/predicate"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/role"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/serviceaccount"
)

// ServiceAccountUpdate is the builder for updating ServiceAccount entities.
type ServiceAccountUpdate struct {
	config
	hooks    []Hook
	mutation *ServiceAccountMutation
}

// Where appends a list predicates to the ServiceAccountUpdate builder.
func (_u *ServiceAccountUpdate) Where(ps ...predicate.ServiceAccount) *ServiceAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ServiceAccountUpdate) SetName(v string) *ServiceAccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ServiceAccountUpdate) SetNillableName(v *string) *ServiceAccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ServiceAccountUpdate) SetDescription(v string) *ServiceAccountUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ServiceAccountUpdate) SetNillableDescription(v *string) *ServiceAccountUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ServiceAccountUpdate) ClearDescription() *ServiceAccountUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *ServiceAccountUpdate) SetTokenHash(v string) *ServiceAccountUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *ServiceAccountUpdate) SetNillableTokenHash(v *string) *ServiceAccountUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetTokenPrefix sets the "token_prefix" field.
func (_u *ServiceAccountUpdate) SetTokenPrefix(v string) *ServiceAccountUpdate {
	_u.mutation.SetTokenPrefix(v)
	return _u
}

// SetNillableTokenPrefix sets the "token_prefix" field if the given value is not nil.
func (_u *ServiceAccountUpdate) SetNillableTokenPrefix(v *string) *ServiceAccountUpdate {
	if v != nil {
		_u.SetTokenPrefix(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ServiceAccountUpdate) SetExpiresAt(v time.Time) *ServiceAccountUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ServiceAccountUpdate) SetNillableExpiresAt(v *time.Time) *ServiceAccountUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ServiceAccountUpdate) ClearExpiresAt() *ServiceAccountUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *ServiceAccountUpdate) SetDisabled(v bool) *ServiceAccountUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *ServiceAccountUpdate) SetNillableDisabled(v *bool) *ServiceAccountUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceAccountUpdate) SetUpdatedAt(v time.Time) *ServiceAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (_u *ServiceAccountUpdate) AddRoleIDs(ids ...int) *ServiceAccountUpdate {
	_u.mutation.AddRoleIDs(ids...)
	return _u
}

// AddRoles adds the "roles" edges to the Role entity.
func (_u *ServiceAccountUpdate) AddRoles(v ...*Role) *ServiceAccountUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleIDs(ids...)
}

// Mutation returns the ServiceAccountMutation object of the builder.
func (_u *ServiceAccountUpdate) Mutation() *ServiceAccountMutation {
	return _u.mutation
}

// ClearRoles clears all "roles" edges to the Role entity.
func (_u *ServiceAccountUpdate) ClearRoles() *ServiceAccountUpdate {
	_u.mutation.ClearRoles()
	return _u
}

// RemoveRoleIDs removes the "roles" edge to Role entities by IDs.
func (_u *ServiceAccountUpdate) RemoveRoleIDs(ids ...int) *ServiceAccountUpdate {
	_u.mutation.RemoveRoleIDs(ids...)
	return _u
}

// RemoveRoles removes "roles" edges to Role entities.
func (_u *ServiceAccountUpdate) RemoveRoles(v ...*Role) *ServiceAccountUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServiceAccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServiceAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServiceAccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := serviceaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceAccountUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := serviceaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ServiceAccount.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := serviceaccount.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "ServiceAccount.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenPrefix(); ok {
		if err := serviceaccount.TokenPrefixValidator(v); err != nil {
			return &ValidationError{Name: "token_prefix", err: fmt.Errorf(`ent: validator failed for field "ServiceAccount.token_prefix": %w`, err)}
		}
	}
	return nil
}

func (_u *ServiceAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(serviceaccount.Table, serviceaccount.Columns, sqlgraph.NewFieldSpec(serviceaccount.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(serviceaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(serviceaccount.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(serviceaccount.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(serviceaccount.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenPrefix(); ok {
		_spec.SetField(serviceaccount.FieldTokenPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(serviceaccount.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(serviceaccount.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(serviceaccount.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(serviceaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   serviceaccount.RolesTable,
			Columns: serviceaccount.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolesIDs(); len(nodes) > 0 && !_u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   serviceaccount.RolesTable,
			Columns: serviceaccount.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   serviceaccount.RolesTable,
			Columns: serviceaccount.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serviceaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServiceAccountUpdateOne is the builder for updating a single ServiceAccount entity.
type ServiceAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServiceAccountMutation
}

// SetName sets the "name" field.
func (_u *ServiceAccountUpdateOne) SetName(v string) *ServiceAccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ServiceAccountUpdateOne) SetNillableName(v *string) *ServiceAccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ServiceAccountUpdateOne) SetDescription(v string) *ServiceAccountUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ServiceAccountUpdateOne) SetNillableDescription(v *string) *ServiceAccountUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ServiceAccountUpdateOne) ClearDescription() *ServiceAccountUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *ServiceAccountUpdateOne) SetTokenHash(v string) *ServiceAccountUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *ServiceAccountUpdateOne) SetNillableTokenHash(v *string) *ServiceAccountUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetTokenPrefix sets the "token_prefix" field.
func (_u *ServiceAccountUpdateOne) SetTokenPrefix(v string) *ServiceAccountUpdateOne {
	_u.mutation.SetTokenPrefix(v)
	return _u
}

// SetNillableTokenPrefix sets the "token_prefix" field if the given value is not nil.
func (_u *ServiceAccountUpdateOne) SetNillableTokenPrefix(v *string) *ServiceAccountUpdateOne {
	if v != nil {
		_u.SetTokenPrefix(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ServiceAccountUpdateOne) SetExpiresAt(v time.Time) *ServiceAccountUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ServiceAccountUpdateOne) SetNillableExpiresAt(v *time.Time) *ServiceAccountUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ServiceAccountUpdateOne) ClearExpiresAt() *ServiceAccountUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *ServiceAccountUpdateOne) SetDisabled(v bool) *ServiceAccountUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *ServiceAccountUpdateOne) SetNillableDisabled(v *bool) *ServiceAccountUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceAccountUpdateOne) SetUpdatedAt(v time.Time) *ServiceAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (_u *ServiceAccountUpdateOne) AddRoleIDs(ids ...int) *ServiceAccountUpdateOne {
	_u.mutation.AddRoleIDs(ids...)
	return _u
}

// AddRoles adds the "roles" edges to the Role entity.
func (_u *ServiceAccountUpdateOne) AddRoles(v ...*Role) *ServiceAccountUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleIDs(ids...)
}

// Mutation returns the ServiceAccountMutation object of the builder.
func (_u *ServiceAccountUpdateOne) Mutation() *ServiceAccountMutation {
	return _u.mutation
}

// ClearRoles clears all "roles" edges to the Role entity.
func (_u *ServiceAccountUpdateOne) ClearRoles() *ServiceAccountUpdateOne {
	_u.mutation.ClearRoles()
	return _u
}

// RemoveRoleIDs removes the "roles" edge to Role entities by IDs.
func (_u *ServiceAccountUpdateOne) RemoveRoleIDs(ids ...int) *ServiceAccountUpdateOne {
	_u.mutation.RemoveRoleIDs(ids...)
	return _u
}

// RemoveRoles removes "roles" edges to Role entities.
func (_u *ServiceAccountUpdateOne) RemoveRoles(v ...*Role) *ServiceAccountUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleIDs(ids...)
}

// Where appends a list predicates to the ServiceAccountUpdate builder.
func (_u *ServiceAccountUpdateOne) Where(ps ...predicate.ServiceAccount) *ServiceAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServiceAccountUpdateOne) Select(field string, fields ...string) *ServiceAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ServiceAccount entity.
func (_u *ServiceAccountUpdateOne) Save(ctx context.Context) (*ServiceAccount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceAccountUpdateOne) SaveX(ctx context.Context) *ServiceAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServiceAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServiceAccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := serviceaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceAccountUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := serviceaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ServiceAccount.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := serviceaccount.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "ServiceAccount.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenPrefix(); ok {
		if err := serviceaccount.TokenPrefixValidator(v); err != nil {
			return &ValidationError{Name: "token_prefix", err: fmt.Errorf(`ent: validator failed for field "ServiceAccount.token_prefix": %w`, err)}
		}
	}
	return nil
}

func (_u *ServiceAccountUpdateOne) sqlSave(ctx context.Context) (_node *ServiceAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(serviceaccount.Table, serviceaccount.Columns, sqlgraph.NewFieldSpec(serviceaccount.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServiceAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serviceaccount.FieldID)
		for _, f := range fields {
			if !serviceaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != serviceaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(serviceaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(serviceaccount.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(serviceaccount.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(serviceaccount.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenPrefix(); ok {
		_spec.SetField(serviceaccount.FieldTokenPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(serviceaccount.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(serviceaccount.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(serviceaccount.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(serviceaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   serviceaccount.RolesTable,
			Columns: serviceaccount.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolesIDs(); len(nodes) > 0 && !_u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   serviceaccount.RolesTable,
			Columns: serviceaccount.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   serviceaccount.RolesTable,
			Columns: serviceaccount.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ServiceAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serviceaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
