// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"temperate/internal/data/ent/ssoprovider"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SSOProviderCreate is the builder for creating a SSOProvider entity.
type SSOProviderCreate struct {
	config
	mutation *SSOProviderMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *SSOProviderCreate) SetName(v string) *SSOProviderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *SSOProviderCreate) SetType(v string) *SSOProviderCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *SSOProviderCreate) SetEnabled(v bool) *SSOProviderCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *SSOProviderCreate) SetNillableEnabled(v *bool) *SSOProviderCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *SSOProviderCreate) SetIcon(v string) *SSOProviderCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *SSOProviderCreate) SetNillableIcon(v *string) *SSOProviderCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *SSOProviderCreate) SetSortOrder(v int) *SSOProviderCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *SSOProviderCreate) SetNillableSortOrder(v *int) *SSOProviderCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *SSOProviderCreate) SetConfig(v map[string]string) *SSOProviderCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SSOProviderCreate) SetCreatedAt(v time.Time) *SSOProviderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SSOProviderCreate) SetNillableCreatedAt(v *time.Time) *SSOProviderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SSOProviderCreate) SetUpdatedAt(v time.Time) *SSOProviderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SSOProviderCreate) SetNillableUpdatedAt(v *time.Time) *SSOProviderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the SSOProviderMutation object of the builder.
func (_c *SSOProviderCreate) Mutation() *SSOProviderMutation {
	return _c.mutation
}

// Save creates the SSOProvider in the database.
func (_c *SSOProviderCreate) Save(ctx context.Context) (*SSOProvider, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SSOProviderCreate) SaveX(ctx context.Context) *SSOProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SSOProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SSOProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SSOProviderCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := ssoprovider.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Icon(); !ok {
		v := ssoprovider.DefaultIcon
		_c.mutation.SetIcon(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := ssoprovider.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ssoprovider.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ssoprovider.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SSOProviderCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SSOProvider.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := ssoprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SSOProvider.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "SSOProvider.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := ssoprovider.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SSOProvider.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "SSOProvider.enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "SSOProvider.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SSOProvider.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SSOProvider.updated_at"`)}
	}
	return nil
}

func (_c *SSOProviderCreate) sqlSave(ctx context.Context) (*SSOProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SSOProviderCreate) createSpec() (*SSOProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &SSOProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ssoprovider.Table, sqlgraph.NewFieldSpec(ssoprovider.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ssoprovider.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(ssoprovider.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(ssoprovider.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(ssoprovider.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(ssoprovider.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(ssoprovider.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ssoprovider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ssoprovider.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// SSOProviderCreateBulk is the builder for creating many SSOProvider entities in bulk.
type SSOProviderCreateBulk struct {
	config
	err      error
	builders []*SSOProviderCreate
}

// Save creates the SSOProvider entities in the database.
func (_c *SSOProviderCreateBulk) Save(ctx context.Context) ([]*SSOProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SSOProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SSOProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SSOProviderCreateBulk) SaveX(ctx context.Context) []*SSOProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SSOProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SSOProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
