// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/predicate"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data/ent/ssoprovider"
)

// SSOProviderDelete is the builder for deleting a SSOProvider entity.
type SSOProviderDelete struct {
	config
	hooks    []Hook
	mutation *SSOProviderMutation
}

// Where appends a list predicates to the SSOProviderDelete builder.
func (_d *SSOProviderDelete) Where(ps ...predicate.SSOProvider) *SSOProviderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SSOProviderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SSOProviderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SSOProviderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ssoprovider.Table, sqlgraph.NewFieldSpec(ssoprovider.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SSOProviderDeleteOne is the builder for deleting a single SSOProvider entity.
type SSOProviderDeleteOne struct {
	_d *SSOProviderDelete
}

// Where appends a list predicates to the SSOProviderDelete builder.
func (_d *SSOProviderDeleteOne) Where(ps ...predicate.SSOProvider) *SSOProviderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SSOProviderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ssoprovider.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SSOProviderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
