// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"log/slog"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/biz"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/conf"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/data"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/registry"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/server"
	"github.com/wuyuetianjian/kratos-template-for-all/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger *slog.Logger) (*kratos.App, func(), error) {
	registrar, cleanup, err := registry.NewRegistrar(confRegistry)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	metrics := server.NewMetrics(confData, logger)
	tracing, cleanup3, err := server.NewTracing(confData, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cron := data.NewCron()
	authRepo := data.NewAuthRepo(dataData)
	ssoProviderRepo := data.NewSSOProviderRepo(dataData)
	sessionRepo := data.NewSessionRepo(dataData)
	auditLogRepo := data.NewAuditLogRepo(dataData)
	settingsRepo := data.NewSettingsRepo(dataData)
	serviceAccountRepo := data.NewServiceAccountRepo(dataData)
	useCase, err := biz.NewUseCase(logger, cron, confServer, confData, authRepo, ssoProviderRepo, sessionRepo, auditLogRepo, settingsRepo, serviceAccountRepo)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	incidentService := service.NewIncidentService(confData, useCase, logger)
	grpcServer := server.NewGRPCServer(confServer, confData, metrics, tracing, useCase, incidentService, logger)
	httpServer := server.NewHTTPServer(confServer, confData, metrics, tracing, useCase, incidentService, logger)
	app := newApp(logger, registrar, dataData, grpcServer, httpServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
