// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Registry      *Registry              `protobuf:"bytes,3,opt,name=registry,proto3" json:"registry,omitempty"`
	Config        *Config                `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetRegistry() *Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *Bootstrap) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,3,opt,name=redis,proto3" json:"redis,omitempty"`
	Api           *Data_API              `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetApi() *Data_API {
	if x != nil {
		return x.Api
	}
	return nil
}

type Registry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Driver         string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Endpoints      []string               `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Namespace      string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Username       string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password       string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Token          string                 `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	Datacenter     string                 `protobuf:"bytes,8,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Group          string                 `protobuf:"bytes,9,opt,name=group,proto3" json:"group,omitempty"`
	Cluster        string                 `protobuf:"bytes,10,opt,name=cluster,proto3" json:"cluster,omitempty"`
	ServiceToken   string                 `protobuf:"bytes,11,opt,name=service_token,json=serviceToken,proto3" json:"service_token,omitempty"`
	Protocol       string                 `protobuf:"bytes,12,opt,name=protocol,proto3" json:"protocol,omitempty"`
	TtlSeconds     int32                  `protobuf:"varint,13,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Kubeconfig     string                 `protobuf:"bytes,14,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	ContextPath    string                 `protobuf:"bytes,15,opt,name=context_path,json=contextPath,proto3" json:"context_path,omitempty"`
	HealthCheck    bool                   `protobuf:"varint,16,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	Heartbeat      bool                   `protobuf:"varint,17,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Weight         int32                  `protobuf:"varint,18,opt,name=weight,proto3" json:"weight,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,19,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	RetryCount     int32                  `protobuf:"varint,20,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	Region         string                 `protobuf:"bytes,21,opt,name=region,proto3" json:"region,omitempty"`
	Zone           string                 `protobuf:"bytes,22,opt,name=zone,proto3" json:"zone,omitempty"`
	Env            string                 `protobuf:"bytes,23,opt,name=env,proto3" json:"env,omitempty"`
	Host           string                 `protobuf:"bytes,24,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Registry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Registry) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Registry) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Registry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Registry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Registry) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Registry) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Registry) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *Registry) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Registry) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Registry) GetServiceToken() string {
	if x != nil {
		return x.ServiceToken
	}
	return ""
}

func (x *Registry) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Registry) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *Registry) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

func (x *Registry) GetContextPath() string {
	if x != nil {
		return x.ContextPath
	}
	return ""
}

func (x *Registry) GetHealthCheck() bool {
	if x != nil {
		return x.HealthCheck
	}
	return false
}

func (x *Registry) GetHeartbeat() bool {
	if x != nil {
		return x.Heartbeat
	}
	return false
}

func (x *Registry) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Registry) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Registry) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Registry) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Registry) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Registry) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Registry) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           *Config_Env            `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`
	Remote        *Config_Remote         `protobuf:"bytes,2,opt,name=remote,proto3" json:"remote,omitempty"`
	Watch         *Config_Watch          `protobuf:"bytes,3,opt,name=watch,proto3" json:"watch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Config) GetEnv() *Config_Env {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Config) GetRemote() *Config_Remote {
	if x != nil {
		return x.Remote
	}
	return nil
}

func (x *Config) GetWatch() *Config_Watch {
	if x != nil {
		return x.Watch
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Driver          string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ReadSources     []string               `protobuf:"bytes,3,rep,name=read_sources,json=readSources,proto3" json:"read_sources,omitempty"`
	MaxIdleConns    int32                  `protobuf:"varint,4,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	MaxOpenConns    int32                  `protobuf:"varint,5,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	ConnMaxLifetime *durationpb.Duration   `protobuf:"bytes,6,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	Debug           bool                   `protobuf:"varint,7,opt,name=debug,proto3" json:"debug,omitempty"`
	AutoMigrate     bool                   `protobuf:"varint,8,opt,name=auto_migrate,json=autoMigrate,proto3" json:"auto_migrate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database) GetReadSources() []string {
	if x != nil {
		return x.ReadSources
	}
	return nil
}

func (x *Data_Database) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Data_Database) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_Database) GetConnMaxLifetime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return nil
}

func (x *Data_Database) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *Data_Database) GetAutoMigrate() bool {
	if x != nil {
		return x.AutoMigrate
	}
	return false
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_internal_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Data_Redis) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Data_API struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Auth            bool                   `protobuf:"varint,1,opt,name=auth,proto3" json:"auth,omitempty"`
	SigningMethod   string                 `protobuf:"bytes,2,opt,name=signing_method,json=signingMethod,proto3" json:"signing_method,omitempty"`
	JwtKey          string                 `protobuf:"bytes,3,opt,name=jwt_key,json=jwtKey,proto3" json:"jwt_key,omitempty"`
	Metrics         bool                   `protobuf:"varint,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	MetricsPath     string                 `protobuf:"bytes,5,opt,name=metrics_path,json=metricsPath,proto3" json:"metrics_path,omitempty"`
	Ratelimit       bool                   `protobuf:"varint,6,opt,name=ratelimit,proto3" json:"ratelimit,omitempty"`
	Tracing         bool                   `protobuf:"varint,7,opt,name=tracing,proto3" json:"tracing,omitempty"`
	TracingEndpoint string                 `protobuf:"bytes,8,opt,name=tracing_endpoint,json=tracingEndpoint,proto3" json:"tracing_endpoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_API) Reset() {
	*x = Data_API{}
	mi := &file_internal_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_API) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_API) ProtoMessage() {}

func (x *Data_API) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_API.ProtoReflect.Descriptor instead.
func (*Data_API) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Data_API) GetAuth() bool {
	if x != nil {
		return x.Auth
	}
	return false
}

func (x *Data_API) GetSigningMethod() string {
	if x != nil {
		return x.SigningMethod
	}
	return ""
}

func (x *Data_API) GetJwtKey() string {
	if x != nil {
		return x.JwtKey
	}
	return ""
}

func (x *Data_API) GetMetrics() bool {
	if x != nil {
		return x.Metrics
	}
	return false
}

func (x *Data_API) GetMetricsPath() string {
	if x != nil {
		return x.MetricsPath
	}
	return ""
}

func (x *Data_API) GetRatelimit() bool {
	if x != nil {
		return x.Ratelimit
	}
	return false
}

func (x *Data_API) GetTracing() bool {
	if x != nil {
		return x.Tracing
	}
	return false
}

func (x *Data_API) GetTracingEndpoint() string {
	if x != nil {
		return x.TracingEndpoint
	}
	return ""
}

type Config_Env struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config_Env) Reset() {
	*x = Config_Env{}
	mi := &file_internal_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config_Env) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Env) ProtoMessage() {}

func (x *Config_Env) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Env.ProtoReflect.Descriptor instead.
func (*Config_Env) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Config_Env) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Config_Env) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type Config_Remote struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Driver         string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Endpoints      []string               `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Path           string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Namespace      string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group          string                 `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	Cluster        string                 `protobuf:"bytes,7,opt,name=cluster,proto3" json:"cluster,omitempty"`
	DataId         string                 `protobuf:"bytes,8,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	AppId          string                 `protobuf:"bytes,9,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Secret         string                 `protobuf:"bytes,10,opt,name=secret,proto3" json:"secret,omitempty"`
	Token          string                 `protobuf:"bytes,11,opt,name=token,proto3" json:"token,omitempty"`
	Username       string                 `protobuf:"bytes,12,opt,name=username,proto3" json:"username,omitempty"`
	Password       string                 `protobuf:"bytes,13,opt,name=password,proto3" json:"password,omitempty"`
	Kubeconfig     string                 `protobuf:"bytes,14,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	Master         string                 `protobuf:"bytes,15,opt,name=master,proto3" json:"master,omitempty"`
	LabelSelector  string                 `protobuf:"bytes,16,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	FieldSelector  string                 `protobuf:"bytes,17,opt,name=field_selector,json=fieldSelector,proto3" json:"field_selector,omitempty"`
	FileGroup      string                 `protobuf:"bytes,18,opt,name=file_group,json=fileGroup,proto3" json:"file_group,omitempty"`
	FileName       string                 `protobuf:"bytes,19,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContextPath    string                 `protobuf:"bytes,20,opt,name=context_path,json=contextPath,proto3" json:"context_path,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,21,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Config_Remote) Reset() {
	*x = Config_Remote{}
	mi := &file_internal_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config_Remote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Remote) ProtoMessage() {}

func (x *Config_Remote) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Remote.ProtoReflect.Descriptor instead.
func (*Config_Remote) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Config_Remote) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Config_Remote) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Config_Remote) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Config_Remote) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Config_Remote) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Config_Remote) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Config_Remote) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Config_Remote) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *Config_Remote) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Config_Remote) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Config_Remote) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Config_Remote) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Config_Remote) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Config_Remote) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

func (x *Config_Remote) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

func (x *Config_Remote) GetLabelSelector() string {
	if x != nil {
		return x.LabelSelector
	}
	return ""
}

func (x *Config_Remote) GetFieldSelector() string {
	if x != nil {
		return x.FieldSelector
	}
	return ""
}

func (x *Config_Remote) GetFileGroup() string {
	if x != nil {
		return x.FileGroup
	}
	return ""
}

func (x *Config_Remote) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Config_Remote) GetContextPath() string {
	if x != nil {
		return x.ContextPath
	}
	return ""
}

func (x *Config_Remote) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type Config_Watch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config_Watch) Reset() {
	*x = Config_Watch{}
	mi := &file_internal_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config_Watch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Watch) ProtoMessage() {}

func (x *Config_Watch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Watch.ProtoReflect.Descriptor instead.
func (*Config_Watch) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{4, 2}
}

func (x *Config_Watch) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Config_Watch) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_internal_conf_conf_proto protoreflect.FileDescriptor

const file_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x18internal/conf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xbb\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x120\n" +
	"\bregistry\x18\x03 \x01(\v2\x14.kratos.api.RegistryR\bregistry\x12*\n" +
	"\x06config\x18\x04 \x01(\v2\x12.kratos.api.ConfigR\x06config\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xa9\a\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x02 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x03 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x12&\n" +
	"\x03api\x18\x01 \x01(\v2\x14.kratos.api.Data.APIR\x03api\x1a\xa9\x02\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12!\n" +
	"\fread_sources\x18\x03 \x03(\tR\vreadSources\x12$\n" +
	"\x0emax_idle_conns\x18\x04 \x01(\x05R\fmaxIdleConns\x12$\n" +
	"\x0emax_open_conns\x18\x05 \x01(\x05R\fmaxOpenConns\x12E\n" +
	"\x11conn_max_lifetime\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x0fconnMaxLifetime\x12\x14\n" +
	"\x05debug\x18\a \x01(\bR\x05debug\x12!\n" +
	"\fauto_migrate\x18\b \x01(\bR\vautoMigrate\x1a\xeb\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x1a\xf9\x01\n" +
	"\x03API\x12\x12\n" +
	"\x04auth\x18\x01 \x01(\bR\x04auth\x12%\n" +
	"\x0esigning_method\x18\x02 \x01(\tR\rsigningMethod\x12\x17\n" +
	"\ajwt_key\x18\x03 \x01(\tR\x06jwtKey\x12\x18\n" +
	"\ametrics\x18\x04 \x01(\bR\ametrics\x12!\n" +
	"\fmetrics_path\x18\x05 \x01(\tR\vmetricsPath\x12\x1c\n" +
	"\tratelimit\x18\x06 \x01(\bR\tratelimit\x12\x18\n" +
	"\atracing\x18\a \x01(\bR\atracing\x12)\n" +
	"\x10tracing_endpoint\x18\b \x01(\tR\x0ftracingEndpoint\"\xb0\x05\n" +
	"\bRegistry\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x1c\n" +
	"\tendpoints\x18\x03 \x03(\tR\tendpoints\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x14\n" +
	"\x05token\x18\a \x01(\tR\x05token\x12\x1e\n" +
	"\n" +
	"datacenter\x18\b \x01(\tR\n" +
	"datacenter\x12\x14\n" +
	"\x05group\x18\t \x01(\tR\x05group\x12\x18\n" +
	"\acluster\x18\n" +
	" \x01(\tR\acluster\x12#\n" +
	"\rservice_token\x18\v \x01(\tR\fserviceToken\x12\x1a\n" +
	"\bprotocol\x18\f \x01(\tR\bprotocol\x12\x1f\n" +
	"\vttl_seconds\x18\r \x01(\x05R\n" +
	"ttlSeconds\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x0e \x01(\tR\n" +
	"kubeconfig\x12!\n" +
	"\fcontext_path\x18\x0f \x01(\tR\vcontextPath\x12!\n" +
	"\fhealth_check\x18\x10 \x01(\bR\vhealthCheck\x12\x1c\n" +
	"\theartbeat\x18\x11 \x01(\bR\theartbeat\x12\x16\n" +
	"\x06weight\x18\x12 \x01(\x05R\x06weight\x12'\n" +
	"\x0ftimeout_seconds\x18\x13 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vretry_count\x18\x14 \x01(\x05R\n" +
	"retryCount\x12\x16\n" +
	"\x06region\x18\x15 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x16 \x01(\tR\x04zone\x12\x10\n" +
	"\x03env\x18\x17 \x01(\tR\x03env\x12\x12\n" +
	"\x04host\x18\x18 \x01(\tR\x04host\"\xe6\x06\n" +
	"\x06Config\x12(\n" +
	"\x03env\x18\x01 \x01(\v2\x16.kratos.api.Config.EnvR\x03env\x121\n" +
	"\x06remote\x18\x02 \x01(\v2\x19.kratos.api.Config.RemoteR\x06remote\x12.\n" +
	"\x05watch\x18\x03 \x01(\v2\x18.kratos.api.Config.WatchR\x05watch\x1a7\n" +
	"\x03Env\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x1a\xde\x04\n" +
	"\x06Remote\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x1c\n" +
	"\tendpoints\x18\x03 \x03(\tR\tendpoints\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05group\x18\x06 \x01(\tR\x05group\x12\x18\n" +
	"\acluster\x18\a \x01(\tR\acluster\x12\x17\n" +
	"\adata_id\x18\b \x01(\tR\x06dataId\x12\x15\n" +
	"\x06app_id\x18\t \x01(\tR\x05appId\x12\x16\n" +
	"\x06secret\x18\n" +
	" \x01(\tR\x06secret\x12\x14\n" +
	"\x05token\x18\v \x01(\tR\x05token\x12\x1a\n" +
	"\busername\x18\f \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\r \x01(\tR\bpassword\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x0e \x01(\tR\n" +
	"kubeconfig\x12\x16\n" +
	"\x06master\x18\x0f \x01(\tR\x06master\x12%\n" +
	"\x0elabel_selector\x18\x10 \x01(\tR\rlabelSelector\x12%\n" +
	"\x0efield_selector\x18\x11 \x01(\tR\rfieldSelector\x12\x1d\n" +
	"\n" +
	"file_group\x18\x12 \x01(\tR\tfileGroup\x12\x1b\n" +
	"\tfile_name\x18\x13 \x01(\tR\bfileName\x12!\n" +
	"\fcontext_path\x18\x14 \x01(\tR\vcontextPath\x12'\n" +
	"\x0ftimeout_seconds\x18\x15 \x01(\x05R\x0etimeoutSeconds\x1a5\n" +
	"\x05Watch\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keysB\x1eZ\x1ctemperate/internal/conf;confb\x06proto3"

var (
	file_internal_conf_conf_proto_rawDescOnce sync.Once
	file_internal_conf_conf_proto_rawDescData []byte
)

func file_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)))
	})
	return file_internal_conf_conf_proto_rawDescData
}

var file_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Data)(nil),                // 2: kratos.api.Data
	(*Registry)(nil),            // 3: kratos.api.Registry
	(*Config)(nil),              // 4: kratos.api.Config
	(*Server_HTTP)(nil),         // 5: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 6: kratos.api.Server.GRPC
	(*Data_Database)(nil),       // 7: kratos.api.Data.Database
	(*Data_Redis)(nil),          // 8: kratos.api.Data.Redis
	(*Data_API)(nil),            // 9: kratos.api.Data.API
	(*Config_Env)(nil),          // 10: kratos.api.Config.Env
	(*Config_Remote)(nil),       // 11: kratos.api.Config.Remote
	(*Config_Watch)(nil),        // 12: kratos.api.Config.Watch
	(*durationpb.Duration)(nil), // 13: google.protobuf.Duration
}
var file_internal_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.registry:type_name -> kratos.api.Registry
	4,  // 3: kratos.api.Bootstrap.config:type_name -> kratos.api.Config
	5,  // 4: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	6,  // 5: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	7,  // 6: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	8,  // 7: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	9,  // 8: kratos.api.Data.api:type_name -> kratos.api.Data.API
	10, // 9: kratos.api.Config.env:type_name -> kratos.api.Config.Env
	11, // 10: kratos.api.Config.remote:type_name -> kratos.api.Config.Remote
	12, // 11: kratos.api.Config.watch:type_name -> kratos.api.Config.Watch
	13, // 12: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	13, // 13: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	13, // 14: kratos.api.Data.Database.conn_max_lifetime:type_name -> google.protobuf.Duration
	13, // 15: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	13, // 16: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_conf_conf_proto_init() }
func file_internal_conf_conf_proto_init() {
	if File_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_internal_conf_conf_proto = out.File
	file_internal_conf_conf_proto_goTypes = nil
	file_internal_conf_conf_proto_depIdxs = nil
}
