server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  api:
    auth: true
    signing_method: HS512
    jwt_key: testKey
    metrics: true
    metrics_path: /metrics
    ratelimit: true
    tracing: true
    tracing_endpoint: localhost:4318
  # database:
  #   driver: mysql
  #   source: root:postgres123@tcp(127.0.0.1:5432)/testdb?parseTime=True&loc=Local
  #   read_sources:
  #     - root:postgres123@tcp(127.0.0.1:5432)/testdb?parseTime=True&loc=Local
  #   max_idle_conns: 10
  #   max_open_conns: 100
  #   conn_max_lifetime: 1h
  #   debug: false
  #   auto_migrate: true
  database:
    driver: postgres
    source: postgres://postgres:postgres123@127.0.0.1:5432/testdb?sslmode=disable
    read_sources:
      - postgres://postgres:postgres123@127.0.0.1:5432/testdb?sslmode=disable
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600s
    debug: false
    auto_migrate: true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    # username: ""
    # password: ""
registry:
  enabled: false
  driver: etcd
  endpoints:
    - 127.0.0.1:2379
  namespace: /microservices
config:
  env:
    enabled: false
    prefix: KRATOS_
  remote:
    enabled: false
    driver: etcd
    endpoints:
      - 127.0.0.1:2379
    path: /temperate/config.yaml
    namespace: default
    group: DEFAULT_GROUP
  watch:
    enabled: true
    keys:
      - server
      - data
      - registry
