// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "username", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "resource_type", Type: field.TypeString, Nullable: true},
		{Name: "resource_name", Type: field.TypeString, Nullable: true},
		{Name: "ip", Type: field.TypeString, Nullable: true},
		{Name: "detail", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
	}
	// AuthModulesColumns holds the columns for the "auth_modules" table.
	AuthModulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "system", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AuthModulesTable holds the schema information for the "auth_modules" table.
	AuthModulesTable = &schema.Table{
		Name:       "auth_modules",
		Columns:    AuthModulesColumns,
		PrimaryKey: []*schema.Column{AuthModulesColumns[0]},
	}
	// AuthPermissionsColumns holds the columns for the "auth_permissions" table.
	AuthPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "action", Type: field.TypeString},
		{Name: "operation", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "system", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "module_permissions", Type: field.TypeInt},
	}
	// AuthPermissionsTable holds the schema information for the "auth_permissions" table.
	AuthPermissionsTable = &schema.Table{
		Name:       "auth_permissions",
		Columns:    AuthPermissionsColumns,
		PrimaryKey: []*schema.Column{AuthPermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "auth_permissions_auth_modules_permissions",
				Columns:    []*schema.Column{AuthPermissionsColumns[7]},
				RefColumns: []*schema.Column{AuthModulesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "permission_action_module_permissions",
				Unique:  true,
				Columns: []*schema.Column{AuthPermissionsColumns[1], AuthPermissionsColumns[7]},
			},
		},
	}
	// AuthRolesColumns holds the columns for the "auth_roles" table.
	AuthRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "system", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AuthRolesTable holds the schema information for the "auth_roles" table.
	AuthRolesTable = &schema.Table{
		Name:       "auth_roles",
		Columns:    AuthRolesColumns,
		PrimaryKey: []*schema.Column{AuthRolesColumns[0]},
	}
	// AuthSSOProvidersColumns holds the columns for the "auth_sso_providers" table.
	AuthSSOProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: false},
		{Name: "icon", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "config", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AuthSSOProvidersTable holds the schema information for the "auth_sso_providers" table.
	AuthSSOProvidersTable = &schema.Table{
		Name:       "auth_sso_providers",
		Columns:    AuthSSOProvidersColumns,
		PrimaryKey: []*schema.Column{AuthSSOProvidersColumns[0]},
	}
	// AuthServiceAccountsColumns holds the columns for the "auth_service_accounts" table.
	AuthServiceAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "token_prefix", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "disabled", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AuthServiceAccountsTable holds the schema information for the "auth_service_accounts" table.
	AuthServiceAccountsTable = &schema.Table{
		Name:       "auth_service_accounts",
		Columns:    AuthServiceAccountsColumns,
		PrimaryKey: []*schema.Column{AuthServiceAccountsColumns[0]},
	}
	// SystemSettingsColumns holds the columns for the "system_settings" table.
	SystemSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Default: ""},
	}
	// SystemSettingsTable holds the schema information for the "system_settings" table.
	SystemSettingsTable = &schema.Table{
		Name:       "system_settings",
		Columns:    SystemSettingsColumns,
		PrimaryKey: []*schema.Column{SystemSettingsColumns[0]},
	}
	// AuthUsersColumns holds the columns for the "auth_users" table.
	AuthUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "disabled", Type: field.TypeBool, Default: false},
		{Name: "system", Type: field.TypeBool, Default: false},
		{Name: "initial_password_used", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AuthUsersTable holds the schema information for the "auth_users" table.
	AuthUsersTable = &schema.Table{
		Name:       "auth_users",
		Columns:    AuthUsersColumns,
		PrimaryKey: []*schema.Column{AuthUsersColumns[0]},
	}
	// AuthUserSessionsColumns holds the columns for the "auth_user_sessions" table.
	AuthUserSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "ip", Type: field.TypeString, Nullable: true},
		{Name: "browser", Type: field.TypeString, Nullable: true},
		{Name: "os", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "kicked_by", Type: field.TypeString, Nullable: true},
		{Name: "login_at", Type: field.TypeTime},
		{Name: "last_access_at", Type: field.TypeTime},
		{Name: "user_sessions", Type: field.TypeInt},
	}
	// AuthUserSessionsTable holds the schema information for the "auth_user_sessions" table.
	AuthUserSessionsTable = &schema.Table{
		Name:       "auth_user_sessions",
		Columns:    AuthUserSessionsColumns,
		PrimaryKey: []*schema.Column{AuthUserSessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "auth_user_sessions_auth_users_sessions",
				Columns:    []*schema.Column{AuthUserSessionsColumns[9]},
				RefColumns: []*schema.Column{AuthUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AuthRolePermissionsColumns holds the columns for the "auth_role_permissions" table.
	AuthRolePermissionsColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeInt},
		{Name: "permission_id", Type: field.TypeInt},
	}
	// AuthRolePermissionsTable holds the schema information for the "auth_role_permissions" table.
	AuthRolePermissionsTable = &schema.Table{
		Name:       "auth_role_permissions",
		Columns:    AuthRolePermissionsColumns,
		PrimaryKey: []*schema.Column{AuthRolePermissionsColumns[0], AuthRolePermissionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "auth_role_permissions_role_id",
				Columns:    []*schema.Column{AuthRolePermissionsColumns[0]},
				RefColumns: []*schema.Column{AuthRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "auth_role_permissions_permission_id",
				Columns:    []*schema.Column{AuthRolePermissionsColumns[1]},
				RefColumns: []*schema.Column{AuthPermissionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// AuthRoleParentsColumns holds the columns for the "auth_role_parents" table.
	AuthRoleParentsColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeInt},
		{Name: "parent_id", Type: field.TypeInt},
	}
	// AuthRoleParentsTable holds the schema information for the "auth_role_parents" table.
	AuthRoleParentsTable = &schema.Table{
		Name:       "auth_role_parents",
		Columns:    AuthRoleParentsColumns,
		PrimaryKey: []*schema.Column{AuthRoleParentsColumns[0], AuthRoleParentsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "auth_role_parents_role_id",
				Columns:    []*schema.Column{AuthRoleParentsColumns[0]},
				RefColumns: []*schema.Column{AuthRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "auth_role_parents_parent_id",
				Columns:    []*schema.Column{AuthRoleParentsColumns[1]},
				RefColumns: []*schema.Column{AuthRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// AuthServiceAccountRolesColumns holds the columns for the "auth_service_account_roles" table.
	AuthServiceAccountRolesColumns = []*schema.Column{
		{Name: "service_account_id", Type: field.TypeInt},
		{Name: "role_id", Type: field.TypeInt},
	}
	// AuthServiceAccountRolesTable holds the schema information for the "auth_service_account_roles" table.
	AuthServiceAccountRolesTable = &schema.Table{
		Name:       "auth_service_account_roles",
		Columns:    AuthServiceAccountRolesColumns,
		PrimaryKey: []*schema.Column{AuthServiceAccountRolesColumns[0], AuthServiceAccountRolesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "auth_service_account_roles_service_account_id",
				Columns:    []*schema.Column{AuthServiceAccountRolesColumns[0]},
				RefColumns: []*schema.Column{AuthServiceAccountsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "auth_service_account_roles_role_id",
				Columns:    []*schema.Column{AuthServiceAccountRolesColumns[1]},
				RefColumns: []*schema.Column{AuthRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// AuthUserRolesColumns holds the columns for the "auth_user_roles" table.
	AuthUserRolesColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "role_id", Type: field.TypeInt},
	}
	// AuthUserRolesTable holds the schema information for the "auth_user_roles" table.
	AuthUserRolesTable = &schema.Table{
		Name:       "auth_user_roles",
		Columns:    AuthUserRolesColumns,
		PrimaryKey: []*schema.Column{AuthUserRolesColumns[0], AuthUserRolesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "auth_user_roles_user_id",
				Columns:    []*schema.Column{AuthUserRolesColumns[0]},
				RefColumns: []*schema.Column{AuthUsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "auth_user_roles_role_id",
				Columns:    []*schema.Column{AuthUserRolesColumns[1]},
				RefColumns: []*schema.Column{AuthRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuditLogsTable,
		AuthModulesTable,
		AuthPermissionsTable,
		AuthRolesTable,
		AuthSSOProvidersTable,
		AuthServiceAccountsTable,
		SystemSettingsTable,
		AuthUsersTable,
		AuthUserSessionsTable,
		AuthRolePermissionsTable,
		AuthRoleParentsTable,
		AuthServiceAccountRolesTable,
		AuthUserRolesTable,
	}
)

func init() {
	AuditLogsTable.Annotation = &entsql.Annotation{
		Table: "audit_logs",
	}
	AuthModulesTable.Annotation = &entsql.Annotation{
		Table: "auth_modules",
	}
	AuthPermissionsTable.ForeignKeys[0].RefTable = AuthModulesTable
	AuthPermissionsTable.Annotation = &entsql.Annotation{
		Table: "auth_permissions",
	}
	AuthRolesTable.Annotation = &entsql.Annotation{
		Table: "auth_roles",
	}
	AuthSSOProvidersTable.Annotation = &entsql.Annotation{
		Table: "auth_sso_providers",
	}
	AuthServiceAccountsTable.Annotation = &entsql.Annotation{
		Table: "auth_service_accounts",
	}
	SystemSettingsTable.Annotation = &entsql.Annotation{
		Table: "system_settings",
	}
	AuthUsersTable.Annotation = &entsql.Annotation{
		Table: "auth_users",
	}
	AuthUserSessionsTable.ForeignKeys[0].RefTable = AuthUsersTable
	AuthUserSessionsTable.Annotation = &entsql.Annotation{
		Table: "auth_user_sessions",
	}
	AuthRolePermissionsTable.ForeignKeys[0].RefTable = AuthRolesTable
	AuthRolePermissionsTable.ForeignKeys[1].RefTable = AuthPermissionsTable
	AuthRoleParentsTable.ForeignKeys[0].RefTable = AuthRolesTable
	AuthRoleParentsTable.ForeignKeys[1].RefTable = AuthRolesTable
	AuthServiceAccountRolesTable.ForeignKeys[0].RefTable = AuthServiceAccountsTable
	AuthServiceAccountRolesTable.ForeignKeys[1].RefTable = AuthRolesTable
	AuthUserRolesTable.ForeignKeys[0].RefTable = AuthUsersTable
	AuthUserRolesTable.ForeignKeys[1].RefTable = AuthRolesTable
}
